// Fetch real NOAA tide predictions for the trip range and write
// src/data/tides.generated.ts. Run in CI before `vite build` (and optionally
// locally with `npm run fetch-tides`).
//
// Source:
//   https://api.tidesandcurrents.noaa.gov/api/prod/datagetter
// Station 8667062 = Kiawah River Bridge, SC.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const STATION_ID = "8667062";
const STATION_NAME = "Kiawah River Bridge, SC";
const START_ISO = "2026-05-17";
const END_ISO = "2026-05-24";
const APP_TAG = "tides-planner-app";

const __dirname = dirname(fileURLToPath(import.meta.url));
const targetPath = resolve(__dirname, "..", "src", "data", "tides.generated.ts");

const url = new URL("https://api.tidesandcurrents.noaa.gov/api/prod/datagetter");
url.searchParams.set("product", "predictions");
url.searchParams.set("application", APP_TAG);
url.searchParams.set("begin_date", START_ISO.replaceAll("-", ""));
url.searchParams.set("end_date", END_ISO.replaceAll("-", ""));
url.searchParams.set("datum", "MLLW");
url.searchParams.set("station", STATION_ID);
url.searchParams.set("time_zone", "lst_ldt");
url.searchParams.set("units", "english");
url.searchParams.set("interval", "hilo");
url.searchParams.set("format", "json");

console.log(`Fetching NOAA predictions for station ${STATION_ID} (${STATION_NAME})`);
console.log(`Range: ${START_ISO} → ${END_ISO}`);
console.log(`URL:   ${url.toString()}`);

const res = await fetch(url, {
  headers: { "User-Agent": `${APP_TAG} (github actions)` },
});

if (!res.ok) {
  console.error(`NOAA fetch failed: HTTP ${res.status} ${res.statusText}`);
  process.exit(1);
}

const body = await res.json();
if (body.error) {
  console.error(`NOAA error: ${body.error.message ?? JSON.stringify(body.error)}`);
  process.exit(1);
}

const preds = body.predictions;
if (!Array.isArray(preds) || preds.length < 8) {
  console.error(`NOAA returned no usable predictions (got ${preds?.length ?? 0})`);
  console.error(JSON.stringify(body, null, 2));
  process.exit(1);
}

const byDate = new Map();
for (const p of preds) {
  const [date, time] = String(p.t).split(" ");
  if (!byDate.has(date)) byDate.set(date, []);
  byDate.get(date).push({
    time,
    displayTime: to12Hour(time),
    type: p.type === "H" ? "High" : "Low",
    heightFt: Number(Number(p.v).toFixed(2)),
  });
}

function to12Hour(hhmm) {
  const [hStr, mStr] = hhmm.split(":");
  let h = Number(hStr);
  const m = Number(mStr);
  const ampm = h >= 12 ? "PM" : "AM";
  h = h % 12;
  if (h === 0) h = 12;
  return `${h}:${String(m).padStart(2, "0")} ${ampm}`;
}

function labelFor(dateISO) {
  const [y, m, d] = dateISO.split("-").map(Number);
  const dt = new Date(Date.UTC(y, m - 1, d, 12));
  return new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    timeZone: "UTC",
  }).format(dt);
}

const NOTES = {
  "2026-05-17": ["Travel / arrival day — keep beach plans flexible."],
  "2026-05-24": ["Travel / departure day."],
};

const dayPlans = [];
const start = new Date(START_ISO + "T00:00:00Z");
const end = new Date(END_ISO + "T00:00:00Z");
for (let cur = new Date(start); cur <= end; cur.setUTCDate(cur.getUTCDate() + 1)) {
  const iso = cur.toISOString().slice(0, 10);
  dayPlans.push({
    date: iso,
    label: labelFor(iso),
    tides: byDate.get(iso) ?? [],
    notes: NOTES[iso],
  });
}

const totalEvents = dayPlans.reduce((n, d) => n + d.tides.length, 0);
console.log(`Parsed ${totalEvents} tide events across ${dayPlans.length} days.`);

const generatedAt = new Date().toISOString();
const fileBody = `// AUTO-GENERATED by scripts/fetch-tides.mjs — do not edit by hand.
// Source: NOAA Tides & Currents API, station ${STATION_ID} (${STATION_NAME}).
// Regenerate with \`npm run fetch-tides\`.

import type { DayPlan } from "./tides";

export const GENERATED_AT: string | null = ${JSON.stringify(generatedAt)};
export const generatedTideDays: DayPlan[] = ${JSON.stringify(dayPlans, null, 2)};
`;

mkdirSync(dirname(targetPath), { recursive: true });
writeFileSync(targetPath, fileBody);
console.log(`Wrote ${targetPath}`);
