// Fetch a 7-day forecast from the U.S. National Weather Service and write
// src/data/weather.generated.ts. Run in CI before `vite build`. Mirrors the
// shape produced by src/utils/runtimeWeather.ts so the same components
// consume either path identically.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const LAT = 32.6133;
const LON = -80.0606;
const APP_TAG = "tides-planner-app";

const __dirname = dirname(fileURLToPath(import.meta.url));
const targetPath = resolve(__dirname, "..", "src", "data", "weather.generated.ts");

const headers = {
  Accept: "application/geo+json",
  "User-Agent": `${APP_TAG} (github actions)`,
};

console.log(`Looking up NWS gridpoint for ${LAT}, ${LON}`);
const pointsRes = await fetch(`https://api.weather.gov/points/${LAT},${LON}`, {
  headers,
});
if (!pointsRes.ok) {
  console.error(`NWS /points failed: HTTP ${pointsRes.status}`);
  writeStub("nws-points-failed");
  process.exit(0);
}
const points = await pointsRes.json();
const forecastUrl = points?.properties?.forecast;
if (typeof forecastUrl !== "string") {
  console.error("NWS /points returned no forecast url");
  writeStub("nws-no-forecast-url");
  process.exit(0);
}

console.log(`Fetching forecast: ${forecastUrl}`);
const fRes = await fetch(forecastUrl, { headers });
if (!fRes.ok) {
  console.error(`NWS forecast failed: HTTP ${fRes.status}`);
  writeStub("nws-forecast-failed");
  process.exit(0);
}
const forecast = await fRes.json();
const periods = forecast?.properties?.periods ?? [];
console.log(`Got ${periods.length} forecast periods.`);

const EMOJI_RULES = [
  [/thunder|t-storm/i, "⛈️"],
  [/snow|flurries/i, "🌨️"],
  [/showers|rain/i, "🌧️"],
  [/drizzle/i, "🌦️"],
  [/fog/i, "🌫️"],
  [/mostly cloudy|overcast/i, "☁️"],
  [/partly (sunny|cloudy)|partly|few clouds/i, "⛅"],
  [/mostly sunny|mostly clear/i, "🌤️"],
  [/sunny|clear/i, "☀️"],
  [/windy|breezy/i, "🌬️"],
];

function emojiFor(label) {
  for (const [re, e] of EMOJI_RULES) if (re.test(label)) return e;
  return "🌥️";
}

function parseMaxMph(windSpeed) {
  if (windSpeed == null) return null;
  if (typeof windSpeed === "number") return windSpeed;
  const nums = String(windSpeed).match(/\d+(?:\.\d+)?/g);
  if (!nums) return null;
  return Math.max(...nums.map(Number));
}

const byDate = new Map();
for (const p of periods) {
  const date = String(p.startTime).slice(0, 10);
  const existing = byDate.get(date) ?? {
    date,
    highF: null,
    lowF: null,
    precipChancePct: null,
    windMphMax: null,
    windFromDir: null,
    shortForecast: "",
    emoji: "",
  };
  if (p.isDaytime) {
    existing.highF = p.temperature;
    existing.shortForecast = p.shortForecast;
    existing.detailedForecast = p.detailedForecast;
    existing.icon = p.icon;
    existing.precipChancePct = p.probabilityOfPrecipitation?.value ?? existing.precipChancePct;
    existing.windMphMax = parseMaxMph(p.windSpeed);
    existing.windFromDir = p.windDirection;
    existing.emoji = emojiFor(p.shortForecast ?? "");
  } else {
    existing.lowF = p.temperature;
    if (!existing.shortForecast) {
      existing.shortForecast = p.shortForecast ?? "";
      existing.emoji = emojiFor(p.shortForecast ?? "");
    }
    if (existing.precipChancePct == null) {
      existing.precipChancePct = p.probabilityOfPrecipitation?.value ?? null;
    }
  }
  byDate.set(date, existing);
}

const days = Array.from(byDate.values()).sort((a, b) => a.date.localeCompare(b.date));
console.log(`Aggregated ${days.length} forecast days.`);

writeWeather(days);

function writeWeather(days) {
  const generatedAt = new Date().toISOString();
  const body = `// AUTO-GENERATED by scripts/fetch-weather.mjs — do not edit by hand.
// Source: NWS api.weather.gov, gridpoint near ${LAT}, ${LON}.

import type { DayWeather } from "../utils/runtimeWeather";

export const WEATHER_GENERATED_AT: string | null = ${JSON.stringify(generatedAt)};
export const generatedWeather: DayWeather[] = ${JSON.stringify(days, null, 2)};
`;
  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, body);
  console.log(`Wrote ${targetPath}`);
}

function writeStub(reason) {
  const body = `// AUTO-GENERATED by scripts/fetch-weather.mjs — fetch failed (${reason}).
// The app will fall back to a runtime NWS fetch when online.

import type { DayWeather } from "../utils/runtimeWeather";

export const WEATHER_GENERATED_AT: string | null = null;
export const generatedWeather: DayWeather[] = [];
`;
  mkdirSync(dirname(targetPath), { recursive: true });
  writeFileSync(targetPath, body);
  console.warn(`Wrote stub weather.generated.ts (${reason})`);
}
