// AUTO-GENERATED by scripts/fetch-tides.mjs.
// This stub ships with an empty array so the app falls back to the
// placeholder data in tides.ts. CI overwrites this file with real NOAA
// predictions before `vite build`.

import type { DayPlan } from "./tides";

export const GENERATED_AT: string | null = null;
export const generatedTideDays: DayPlan[] = [];
