// AUTO-GENERATED by scripts/fetch-weather.mjs — fetch failed (nws-points-failed).
// The app will fall back to a runtime NWS fetch when online.

import type { DayWeather } from "../utils/runtimeWeather";

export const WEATHER_GENERATED_AT: string | null = null;
export const generatedWeather: DayWeather[] = [];
